service: serverless-pdf-puppeteer
frameworkVersion: "3"

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  profile: hotpuma

  apiGateway:
    binaryMediaTypes:
      - "application/pdf"
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: "yarn"
  location:
    dev:  .webpack/service

  serverless-offline:
    location: .webpack/service
    basePath: /

  customDomain:
    domainName: labs.mianio.com
    basePath: demo
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  give-me-the-pdf:
    handler: functions/pdf.generate
    events:
      - http:
          path: puppeteer/pdf
          method: get
          cors: true
